name: python devcontainer

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  TAG_STEM: predictables-api
  TEST_TAG: test
  LATEST_TAG: latest
  DOCKERFILE_FOLDER: ./api/docker
  MAJOR_VERSION: 1
  DSLIM_HTTP_PROBE: false
  DOCKERHUB_REPO_OWNER: aaweaver9
  DOCKERHUB_REPO: aaweaver9/predictables-api

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    needs: login
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build test image
      - name: Build and export to Docker
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          image: ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }}
          registry: docker.io
          dockerfile: ${{ env.DOCKERFILE_FOLDER }}/${{ env.TAG_STEM }}.Dockerfile
          pushImage: false
          tags: test

      # If the test passed, build the full-size images for all platforms
      - uses: mr-smithers-excellent/docker-build-push@v6.3
        name: Build full-sized images
        with:
          image: ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }}
          registry: docker.io
          dockerfile: ${{ env.DOCKERFILE_FOLDER }}/${{ env.TAG_STEM }}.Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{ env.LATEST_TAG }}, v${{ env.MAJOR_VERSION }}.${{ github.run_number }}

      # Delete the test image
      - name: Delete the test image
        run: |
          docker image rm ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }}:${{ env.TEST_TAG }}

      # Delete the slim image
      - name: Delete the slim image
        run: |
          docker image rm ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }}:slim

      # Push full-size images to Docker Hub
      - name: Push full-size images to Docker Hub
        run: |
          docker image push ${{ env.DOCKERHUB_REPO_OWNER }}/${{ env.TAG_STEM }} --all-tags
